sudo: required
services:
  - docker

language: go
go:
  - 1.9
  - 1.10.x
  - tip

env:
  - GO15VENDOREXPERIMENT=1

matrix:
  allow_failures:
    - go: tip

before_install:
  - docker pull opensuse:42.3
  - docker pull alpine:latest
  - docker pull busybox:latest
  - make build_integration_tests

before_script:
  - go get github.com/golang/lint/golint

script:
  - make checks
  - go test -v
  - make test_integration
