FROM golang:1.5.0

RUN go get github.com/mssola/climate
RUN go get golang.org/x/tools/cmd/cover
RUN go get golang.org/x/tools/cmd/vet
RUN go get github.com/golang/lint/golint
RUN go get github.com/kisielk/errcheck
RUN go get github.com/tools/godep

WORKDIR /go/src/github.com/SUSE/zypper-docker
ENV GOPATH=/go:/go/src/github.com/SUSE/zypper-docker/Godeps/_workspace/

RUN useradd -m travis
USER travis
