FROM opensuse:42.3
MAINTAINER Flavio Castelli <fcastelli@suse.com>

RUN zypper ar obs://Virtualization:containers/openSUSE_Leap_42.3 containers
RUN zypper --gpg-auto-import-keys ref
RUN zypper -n in --no-recommends \
  ca-certificates-mozilla \
  docker-client \
  ruby \
  ruby-devel \
  libffi48-devel \
  make \
  gcc
RUN zypper -n up ca-certificates-mozilla ca-certificates

WORKDIR /code

COPY Gemfile /code/Gemfile
RUN gem install bundle
RUN bundler.ruby2.1 install --retry=3

ENV PATH=/code:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
