FROM opensuse:13.2
MAINTAINER Flavio Castelli <fcastelli@suse.com>

RUN zypper ar obs://Virtualization:containers/openSUSE_13.2 containers
RUN zypper --gpg-auto-import-keys ref
RUN zypper -n in --no-recommends \
  docker-client \
  ruby \
  ruby-devel \
  libffi48-devel \
  make \
  gcc

WORKDIR /code

COPY Gemfile /code/Gemfile
RUN gem install bundle
RUN bundler.ruby2.1 install --retry=3

ENV PATH=/code:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
